### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by deltaidea** [tjvr/moo#49]
Thanks for the lexer!
Could you please provide types for TypeScript users?

I'm willing to make a PR later if someone would tell me about all the exported stuff. I'm just a beginner with Nearly and I only use `moo.compile()` so far.

**Comment by tjvr** [comment]
We're not going to provide TypeScript definitions—I don't use TS myself!—but you're welcome to publish type definitions as a separate package. :-)

With the exception of `has`, you should find the readme documents all the exports. :-)

**Comment by deltaidea** [comment]
Fair enough, I'll see if I can submit package `@types/moo`. Thanks!

**Comment by MofX** [comment]
Are you still against providing typings with moo?
Using DefinitelyTyped is cumbersome... I can't use moo with typescript without replacing the typings myself, because the once submitted by deltaidea are outdated and I'm still waiting for my pull request to be merged. It would be a lot easier if the typings are just published together with moo. Even if they also get outdated, it is easier to update them here.

**Comment by tjvr** [comment]
> Are you still against providing typings with moo?

Sorry, we still don't want to do this.
